### ISSUE TITLE
Multimodal Reference mapping error using the MapQuery ()

### ISSUE THREAD

**Issue by Ewura-Esi** [yuchaojiang/TRIPOD#11]
I am trying to reanalyze the dataset used in your paper using the code provide from the tutorial. I get this warning anytime I use the MapQuery function. Kindly see the code below and the warning outcome

pbmc <- MapQuery(
+   anchorset = anchors,
+   query = pbmc,
+   reference = reference,
+   refdata = list(
+     celltype.l1 = "celltype.l1",
+     celltype.l2 = "celltype.l2",
+     predicted_ADT = "ADT"
+   ),
+   reference.reduction = "spca", 
+ )
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Predicting cell labels
Warning: Layer counts isn't present in the assay object; returning NULL
Predicting cell labels
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Warning: Layer counts isn't present in the assay object; returning NULL
Transfering 228 features onto reference data
predicted_ADT already present in query. Storing as predicted_predicted_ADT
Warning: Layer counts isn't present in the assay object; returning NULL
Warning: Layer counts isn't present in the assay object; returning NULL
Warning: Layer counts isn't present in the assay object; returning NULL
  |                                                  | 0 % ~calculating  
Integrating dataset 2 with reference dataset
Finding integration vectors
Integrating data
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=03s  
Warning message:
Key 'predictedADT_' taken, using 'predictedpredictedadt_' instead

**Comment by yuchaojiang** [comment]
It seems that you've already transferred the labels and the slot predicted_ADT has been taken. This step is to infer the cell types of the PBMC multiomics data from an existing reference, and is not the core for TRIPOD.
