### ISSUE TITLE
Error: argument slot not provided, e18 <- SetAssayData(e18, assay = "ATAC", slot = "motifs", new.data = motif.object)

### ISSUE THREAD

**Issue by karamveerverma37** [yuchaojiang/TRIPOD#12]
I an getting error while running step2, runChromVAR om mESC data. I have loaded seurat and signac versions as given in tutorial.
library(Seurat, lib.loc = "~/R/seurat_v4_library")
library(Signac, lib.loc = "~/R/seurat_v4_library/")
library(JASPAR2020)
library(TFBSTools)

library(GenomicRanges)
library(dplyr)
library(ggplot2)
library(EnsDb.Mmusculus.v79)
library(GenomeInfoDb)
library(patchwork)
library(chromVAR)
library(motifmatchr)
library(BSgenome.Mmusculus.UCSC.mm10)

# read in data
e18 <- readRDS("e18.rds")

# get motif data
pfm.set <- getMatrixSet(
  x = JASPAR2020,
  opts = list(species = 9606, all_versions = FALSE))

pfm.olig2 <- PFMatrix(
  ID = "PFM.Olig2",
  name = "Olig2",
  strand = "+",
  bg = c(A = 0.25, C = 0.25, G = 0.25, T = 0.25),
  tags = list(
    species = "10090",
    tax_group = "vertebrates"),
  profileMatrix = matrix(
    c(0L,  1L, 0L,  0L,  0L,  0L, # A
      1L, 0L,  0L, 1L,  0L,  0L, # C
      0L,  0L,  1L,  0L, 0L,  1L, # G
      0L,  0L,  0L,  0L,  1L, 0L), # T
    byrow = TRUE, nrow = 4,
    dimnames=list(c("A", "C", "G", "T")))
)
pfm.set <- pfm.set[-which(sapply(pfm.set, function(x) x@name == "OLIG2"))]
pfm.set$PFM.Olig2 <- pfm.olig2
motif.matrix <- CreateMotifMatrix(
  features = granges(e18),
  pwm = pfm.set,
  genome = "mm10",
  use.counts = FALSE
)

motif.object <- CreateMotifObject(data = motif.matrix, pwm = pfm.set)
e18 <- SetAssayData(e18, assay = "ATAC", slot = "motifs", new.data = motif.object)

e18 <- RunChromVAR(
  object = e18,
  genome = BSgenome.Mmusculus.UCSC.mm10
)

saveRDS(e18,"e18.chromvar.rds")

**Comment by yuchaojiang** [comment]
Which step did you run into an issues? The error you had is because your object did not have an ATAC assay.

**Comment by karamveerverma37** [comment]
Thanks for the suggestion. However, I have checked my object and it has ATAC Assay. Iam getting an error before running RunChomVAR command.
> e18 <- SetAssayData(e18, assay = "ATAC", slot = "motifs", new.data = motif.object)
**Error in SetAssayData.ChromatinAssay(object = object[[assay]], layer = layer,  : 
  argument "slot" is missing, with no default**
In addition: Warning message:
The `slot` argument of `SetAssayData()` is deprecated as of SeuratObject 5.0.0.
ℹ Please use the `layer` argument instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
> e18
An object of class Seurat 
205868 features across 2000 samples within 3 assays 
Active assay: ATAC (187120 features, 187120 variable features)
 2 layers present: counts, data
 2 other assays present: RNA, SCT
 5 dimensional reductions calculated: pca, umap.rna, lsi, umap.atac, wnn.umap

Here is how I have generated e18 object: setwd("~/Multi_omics_GRN/TRIPOD/mESC_data/test_TRIPOD/filtered/2000cells")
# load packages

library(Seurat, lib.loc = "~/R/seurat_v4_library")
library(Signac, lib.loc = "~/R/seurat_v4_library/")
library(GenomicRanges)
library(dplyr)
library(ggplot2)
library(EnsDb.Mmusculus.v79)
library(GenomeInfoDb)
library(patchwork)
library(biovizBase)


# extract RNA and ATAC data
#rna.counts <- inputdata.10x$`Gene Expression`
#atac.counts <- inputdata.10x$Peaks
rna_data <- read.csv("subsampled_RNA_2000.csv", row.names = 1)
atac_data <- read.csv("subsampled_ATAC_2000.csv", row.names = 1)
View(rna_data)
# create a Seurat object
e18 <- CreateSeuratObject(counts = rna_data)
#e18[["percent.mt"]] <- PercentageFeatureSet(e18, pattern = "^mt-")
e18

# add in the ATAC-seq data
grange.counts <- StringToGRanges(rownames(atac_data), sep = c(":", "-"))
grange.counts
grange.use <- seqnames(grange.counts) %in% standardChromosomes(grange.counts)
atac.counts <- atac_data[as.vector(grange.use), ]
dim(atac.counts)
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Mmusculus.v79)
seqlevelsStyle(annotations) <- "UCSC"
genome(annotations) <- "mm10"
#file <- "e18_mouse_brain_fresh_5k_atac_fragments.tsv.gz"
#path <- file.path(dir.in, file)
chrom.assay <- CreateChromatinAssay(
  counts = atac.counts,
  sep = c(":", "-"),
  genome = 'mm10',
  min.cells = 10,
  annotation = annotations
)
chrom.assay

e18[["ATAC"]] <- chrom.assay

# load cell type labels
cell_label <- rep("mESC",1000)
cell_label
e18$label <- cell_label
# perform RNA analysis
DefaultAssay(e18) <- "RNA"
e18 <- SCTransform(e18, verbose = FALSE)
e18 <- RunPCA(e18)
e18	<- RunUMAP(e18, reduction = "pca", dims = 1:50,
               reduction.name = "umap.rna", reduction.key = "rnaUMAP_")

e18
# perform ATAC analysis
DefaultAssay(e18) <- "ATAC"
e18 <- RunTFIDF(e18)
e18 <- FindTopFeatures(e18, min.cutoff = "q0")
e18 <- RunSVD(e18)
# exclude the first dimension as this is typically correlated with sequencing depth
e18 <- RunUMAP(e18, reduction = "lsi", dims = 2:50,
               reduction.name = "umap.atac", reduction.key = "atacUMAP_")

# calculate a WNN graph
e18 <- FindMultiModalNeighbors(e18, reduction.list = list("pca", "lsi"),
                               dims.list = list(1:50, 2:50))
e18 <- RunUMAP(e18, nn.name = "weighted.nn",
               reduction.name = "wnn.umap", reduction.key = "wnnUMAP_")

#generate umap for sanity check
p1 <- DimPlot(e18, reduction = "umap.rna",  group.by = "label",
              label = TRUE, label.size = 2.5, repel = TRUE) +
  ggtitle("RNA")
p2 <- DimPlot(e18, reduction = "umap.atac",  group.by = "label",
              label = TRUE, label.size = 2.5, repel = TRUE) +
  ggtitle("ATAC")
p3 <- DimPlot(e18, reduction = "wnn.umap", group.by = "label",
              label = TRUE, label.size = 2.5, repel = TRUE) +
  ggtitle("WNN")
#p1 + p2 + p3 & NoLegend() & theme(plot.title = element_text(hjust = 0.5))

# convert the cell type data to factors
levels.celltype <- "mESC"
#e18$celltype <- factor(e18$celltype, levels = levels.celltype)
e18$celltype <- "mESC"
saveRDS(e18,"e18.rds")
e18

library(JASPAR2020)
library(TFBSTools)
# read in data
e18 <- readRDS("e18.rds")
e18
# get motif data
pfm.set <- getMatrixSet(
  x = JASPAR2020,
  opts = list(species = 9606, all_versions = FALSE))

pfm.olig2 <- PFMatrix(
  ID = "PFM.Olig2",
  name = "Olig2",
  strand = "+",
  bg = c(A = 0.25, C = 0.25, G = 0.25, T = 0.25),
  tags = list(
    species = "10090",
    tax_group = "vertebrates"),
  profileMatrix = matrix(
    c(0L,  1L, 0L,  0L,  0L,  0L, # A
      1L, 0L,  0L, 1L,  0L,  0L, # C
      0L,  0L,  1L,  0L, 0L,  1L, # G
      0L,  0L,  0L,  0L,  1L, 0L), # T
    byrow = TRUE, nrow = 4,
    dimnames=list(c("A", "C", "G", "T")))
)
pfm.set <- pfm.set[-which(sapply(pfm.set, function(x) x@name == "OLIG2"))]
pfm.set$PFM.Olig2 <- pfm.olig2

motif.matrix <- CreateMotifMatrix(
  features = granges(e18),
  pwm = pfm.set,
  genome = "mm10",
  use.counts = FALSE
)
e18
motif.object <- CreateMotifObject(data = motif.matrix, pwm = pfm.set)
e18 <- SetAssayData(e18, assay = "ATAC", slot = "motifs", new.data = motif.object)

e18 <- RunChromVAR(
  object = e18,
  genome = BSgenome.Mmusculus.UCSC.mm10
)

saveRDS(e18,"e18.chromvar.rds")
e18

**Comment by yuchaojiang** [comment]
It seems that slot is deprecated in Seurat 5.0.0 try layer instead... You might need to change the following commands here and there with this change but it's mostly just some wrapper changes. Or try using Seurat 4

**Comment by karamveerverma37** [comment]
I am using Seurat4. Even I provide layer, it gives the same error "the argument slot not provided".
