### ISSUE TITLE
About ct=read.table('celltype_skin.txt', header=T, sep='t')  and the fragments <- "./SNARE_seq/fragments.sort.bed.gz" file 

### ISSUE THREAD

**Issue by goodstudy28** [yuchaojiang/TRIPOD#13]
Hi TRIPOD team,
paper looked really cool! So I wanted to try and run on some of my own data, but I'm having some difficulty, can you tell me how the ct=read.table('celltype_skin.txt', header=T, sep='t') file and the fragments <- "./SNARE_seq/fragments.sort.bed.gz" file are obtained? Thanks!

**Comment by yuchaojiang** [comment]
I believe these are processed by ourselves. Please email me yuchaojiang at tamu dot edu and I can share a copy.

**Comment by goodstudy28** [comment]
Thank you very much, I have emailed you.
