### ISSUE TITLE
Can TRIPOD be used on an unpaired multiomic dataset?

### ISSUE THREAD

**Issue by liyang24** [yuchaojiang/TRIPOD#6]
Hi !
i wonder if TRIPOD be used on single-cell RNA/ATAC data obtained by sequencing alone,Or can only be used for sigle-cell ATAC/RNA multiomic data?
thanks

**Comment by yuchaojiang** [comment]
Hi by default it is for scRNA+ATAC in the same cells. You can match the cells (one cell from scRNA-seq <--> one cell from scATAC-seq with one-on-one non-overlapping mapping) and treat them as if they were multiomics and use TRIPOD, although I have to say a lot of the times this matching/mapping is non-trivial.
