### ISSUE TITLE
error in xymat.list fitmodel 

### ISSUE THREAD

**Issue by gnwwanne** [yuchaojiang/TRIPOD#8]
I got an error when trying to implement the fitModel function on xymats.list function. 
bplapply(xymats.list,fitModel, model.name="TRIPOD", match.by="Xt" 

I got this error:
Error in 1:ncol(xyamts$Xt): argument of legnth 0 

Do you have any suggestion on how to fix this

**Comment by yuchaojiang** [comment]
Hi,

It's hard to tell from only the error you showed.

Most likely your xymats (the elements in xymats.list) does not have an Xt component stored in it.

Did all previous steps finish without errors?

**Comment by gnwwanne** [comment]
Sorry for the late reply. Yes, the previous steps finished without any errors. when I looked at the xymats.list, I found that some of the genes did not have Xt or Yt component stored in it. Do you have any idea at which step of the analysis this could have occurred?
________________________________

**Comment by yuchaojiang** [comment]
I would double check the previous step that generates xymat.list. It also loops through all the genes. It might be that these genes do not have TFs with binding sites in the candidate peak regions.

From: gnwwanne ***@***.***>
Date: Tuesday, September 5, 2023 at 1:04 PM
To: yuchaojiang/TRIPOD ***@***.***>
Cc: Jiang, Yuchao ***@***.***>, State change ***@***.***>
Subject: Re: [yuchaojiang/TRIPOD] error in xymat.list fitmodel (Issue #8)
Sorry for the late reply. Yes, the previous steps finished without any errors. when I looked at the xymats.list, I found that some of the genes did not have Xt or Yt component stored in it. Do you have any idea at which step of the analysis this could have occurred?
________________________________

**Comment by gnwwanne** [comment]
Do you have any ideas on how to remove genes that do not have a transcription binding sites in their peak candidate regions from the xymats.list matrix list ?
________________________________

**Comment by 1QiGuo** [comment]
Hi, I also met the same issue. Some of the genes does not have Xt or Yt component stored in it and the function `fitModel` can not be run successufully. Can you give any suggestion on this? Thanks.

**Comment by yuchaojiang** [comment]
> Hi, I also met the same issue. Some of the genes does not have Xt or Yt component stored in it and the function `fitModel` can not be run successufully. Can you give any suggestion on this? Thanks.

Hi, @1QiGuo  If everything is coded correctly, this means that the gene does not have a peak in the window that you specified (e.g., 100Kb up and downstream of TSS) and/or in that peak there is no known TF binding sites. You can try enlarge the window if needed.

**Comment by 1QiGuo** [comment]
Thanks.
