### ISSUE TITLE
Query regarding plotting Coverage Plots

### ISSUE THREAD

**Issue by raunakkar** [yuchaojiang/TRIPOD#9]
First of all, thank you for making this amazing package to help mitigate multiome data analysis. It is of humongous help.
I was wondering how to generate the coverage plots with the peak accessibility, chip-seq tracks, enhancer tracks, h3k27 tracks alongwith the target gene and TF expression combined with TRIPOD links? I could not find a corresponding code for the same in the scripts provided.  This is in reference to figure 4a and 5c of the pre-print manuscript.
It would be of much help if any suggestions could be provided.
Thank you

**Comment by yuchaojiang** [comment]
Hi,

We used SUSHI to make the plots. You might also try https://phanstiellab.github.io/plotgardener/

Yuchao

**Comment by raunakkar** [comment]
Thank you for the suggestions. It is quite useful. But would it be possible to share the code that was used to generate the plots in the TRIPOD manuscript?
Thank you again.
